- name: Show versions for each device
  hosts: switches, routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: run show interfaces
      ios_command:
        commands: show ip interface brief
      register: output

    - name: print output
      debug:
        var: output.stdout_lines