- name: Backup Router Running Configuration
  hosts: routers, switches
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Backup running config
      ios_config:
        backup: true
        backup_options:
          dir_path: /home/pinhead/devnet/project4
