- name: VLAN configuration
  hosts: switchs
  gather_facts: false
  connection: network_cli
  tasks:
    - name: create VLANs
      ios-command:
        commands:
          - conf t
          - vlan 10
          - name Management
          - vlan 20
          - name Office
          - end
    - name: Assign ports
      ios-command:
        commands:
          - conf t
          - int f0/23
          - switchport mode access
          - switchport access vlan 10
          - int f0/24
          - switchport mode access
          - switchport access vlan 20
          - end